"""Added reviews and total_purchases to Product model

Revision ID: b40071774064
Revises: 
Create Date: 2024-10-24 02:27:09.223947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40071774064'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviews', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('total_purchases', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('total_purchases')
        batch_op.drop_column('reviews')

    # ### end Alembic commands ###
